// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pubsub_schemas/enriched_event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrichedEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId       string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Signature        string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Received         string                 `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	Event            string                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	Payload          string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	EnterpriseId     string                 `protobuf:"bytes,6,opt,name=enterprise_id,json=enterpriseId,proto3" json:"enterprise_id,omitempty"`
	EnterpriseName   string                 `protobuf:"bytes,7,opt,name=enterprise_name,json=enterpriseName,proto3" json:"enterprise_name,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,8,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,9,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	RepositoryId     string                 `protobuf:"bytes,10,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	RepositoryName   string                 `protobuf:"bytes,11,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrichedEvent) Reset() {
	*x = EnrichedEvent{}
	mi := &file_pubsub_schemas_enriched_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedEvent) ProtoMessage() {}

func (x *EnrichedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_schemas_enriched_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedEvent.ProtoReflect.Descriptor instead.
func (*EnrichedEvent) Descriptor() ([]byte, []int) {
	return file_pubsub_schemas_enriched_event_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichedEvent) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *EnrichedEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EnrichedEvent) GetReceived() string {
	if x != nil {
		return x.Received
	}
	return ""
}

func (x *EnrichedEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *EnrichedEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EnrichedEvent) GetEnterpriseId() string {
	if x != nil {
		return x.EnterpriseId
	}
	return ""
}

func (x *EnrichedEvent) GetEnterpriseName() string {
	if x != nil {
		return x.EnterpriseName
	}
	return ""
}

func (x *EnrichedEvent) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EnrichedEvent) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *EnrichedEvent) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *EnrichedEvent) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

var File_pubsub_schemas_enriched_event_proto protoreflect.FileDescriptor

const file_pubsub_schemas_enriched_event_proto_rawDesc = "" +
	"\n" +
	"#pubsub_schemas/enriched_event.proto\"\x8c\x03\n" +
	"\rEnrichedEvent\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1a\n" +
	"\breceived\x18\x03 \x01(\tR\breceived\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12#\n" +
	"\renterprise_id\x18\x06 \x01(\tR\fenterpriseId\x12'\n" +
	"\x0fenterprise_name\x18\a \x01(\tR\x0eenterpriseName\x12'\n" +
	"\x0forganization_id\x18\b \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\t \x01(\tR\x10organizationName\x12#\n" +
	"\rrepository_id\x18\n" +
	" \x01(\tR\frepositoryId\x12'\n" +
	"\x0frepository_name\x18\v \x01(\tR\x0erepositoryNameB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_pubsub_schemas_enriched_event_proto_rawDescOnce sync.Once
	file_pubsub_schemas_enriched_event_proto_rawDescData []byte
)

func file_pubsub_schemas_enriched_event_proto_rawDescGZIP() []byte {
	file_pubsub_schemas_enriched_event_proto_rawDescOnce.Do(func() {
		file_pubsub_schemas_enriched_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsub_schemas_enriched_event_proto_rawDesc), len(file_pubsub_schemas_enriched_event_proto_rawDesc)))
	})
	return file_pubsub_schemas_enriched_event_proto_rawDescData
}

var file_pubsub_schemas_enriched_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubsub_schemas_enriched_event_proto_goTypes = []any{
	(*EnrichedEvent)(nil), // 0: EnrichedEvent
}
var file_pubsub_schemas_enriched_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubsub_schemas_enriched_event_proto_init() }
func file_pubsub_schemas_enriched_event_proto_init() {
	if File_pubsub_schemas_enriched_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsub_schemas_enriched_event_proto_rawDesc), len(file_pubsub_schemas_enriched_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubsub_schemas_enriched_event_proto_goTypes,
		DependencyIndexes: file_pubsub_schemas_enriched_event_proto_depIdxs,
		MessageInfos:      file_pubsub_schemas_enriched_event_proto_msgTypes,
	}.Build()
	File_pubsub_schemas_enriched_event_proto = out.File
	file_pubsub_schemas_enriched_event_proto_goTypes = nil
	file_pubsub_schemas_enriched_event_proto_depIdxs = nil
}
