// Copyright 2023 The Authors (see AUTHORS file)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pubsub_schemas/event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Received      string                 `protobuf:"bytes,3,opt,name=received,proto3" json:"received,omitempty"`
	Event         string                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pubsub_schemas_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pubsub_schemas_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pubsub_schemas_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *Event) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Event) GetReceived() string {
	if x != nil {
		return x.Received
	}
	return ""
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_pubsub_schemas_event_proto protoreflect.FileDescriptor

const file_pubsub_schemas_event_proto_rawDesc = "" +
	"\n" +
	"\x1apubsub_schemas/event.proto\"\x92\x01\n" +
	"\x05Event\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1a\n" +
	"\breceived\x18\x03 \x01(\tR\breceived\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayloadB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_pubsub_schemas_event_proto_rawDescOnce sync.Once
	file_pubsub_schemas_event_proto_rawDescData []byte
)

func file_pubsub_schemas_event_proto_rawDescGZIP() []byte {
	file_pubsub_schemas_event_proto_rawDescOnce.Do(func() {
		file_pubsub_schemas_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsub_schemas_event_proto_rawDesc), len(file_pubsub_schemas_event_proto_rawDesc)))
	})
	return file_pubsub_schemas_event_proto_rawDescData
}

var file_pubsub_schemas_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pubsub_schemas_event_proto_goTypes = []any{
	(*Event)(nil), // 0: Event
}
var file_pubsub_schemas_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pubsub_schemas_event_proto_init() }
func file_pubsub_schemas_event_proto_init() {
	if File_pubsub_schemas_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsub_schemas_event_proto_rawDesc), len(file_pubsub_schemas_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pubsub_schemas_event_proto_goTypes,
		DependencyIndexes: file_pubsub_schemas_event_proto_depIdxs,
		MessageInfos:      file_pubsub_schemas_event_proto_msgTypes,
	}.Build()
	File_pubsub_schemas_event_proto = out.File
	file_pubsub_schemas_event_proto_goTypes = nil
	file_pubsub_schemas_event_proto_depIdxs = nil
}
