name: 'deploy to REPLACE_CUSTOM_NAME'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'REPLACE_SUBDIRECTORY/**'
  workflow_dispatch:

env:
  WIF_PROVIDER: 'REPLACE_WIF_PROVIDER'
  WIF_SERVICE_ACCOUNT: 'REPLACE_WIF_SERVICE_ACCOUNT'


# Don't cancel in progress since we don't want to have half-baked releases.
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-release'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  release_and_deploy:
    runs-on: 'ubuntu-latest'
    environment: 'REPLACE_CUSTOM_NAME'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4

      - name: 'Install crane'
        env:
          VERSION: 'v0.19.1'
        run: |-
          curl -fsL https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_Linux_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin crane

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c' # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.WIF_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@98ddc00a17442e89a24bbf282954a3b65ce6d200' # ratchet:google-github-actions/setup-gcloud@v2

      - uses: 'docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20' # ratchet:docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: 'us-docker.pkg.dev'

      - name: 'Deploy'
        run: 'REPLACE_SUBDIRECTORY/deploy.sh'
        env:
          PROJECT_ID: 'REPLACE_PROJECT_ID'
          REGION: 'REPLACE_REGION'
          WEBHOOK_SERVICE_NAME: 'REPLACE_WEBHOOK_SERVICE_NAME'
          RETRY_SERVICE_NAME: 'REPLACE_RETRY_SERVICE_NAME'
