# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: 'cli.abcxyz.dev/v1beta3'
kind: 'Template'

desc: 'Generate the components necessary to deploy GitHub Metrics Aggregator'

inputs:
  - name: 'custom_name'
    desc: 'A custom name for GitHub Metrics Aggregator'
    default: 'github-metrics'
  - name: 'wif_provider'
    desc: 'The Google Cloud workload identity federation provider for GitHub Metrics Aggregator'
  - name: 'wif_service_account'
    desc: 'The Google Cloud service account for GitHub Metrics Aggregator'
    rules:
      - rule: 'gcp_matches_service_account(wif_service_account)'
  - name: 'project_id'
    desc: 'The Google Cloud project ID containing GitHub Metrics Aggregator'
    rules:
      - rule: 'gcp_matches_project_id(project_id)'
  - name: 'full_image_name'
    desc: 'The full image name, excluding the version tag'
  - name: 'region'
    desc: 'The region of the GitHub Metrics Aggregator Cloud Run service'
  - name: 'webhook_service_name'
    desc: 'The name of the GitHub Metrics Aggregator webhook Cloud Run service'
  - name: 'retry_service_name'
    desc: 'The name of the GitHub Metrics Aggregator retry Cloud Run service'

steps:
  - desc: 'Include required Dockerfiles and configs'
    action: 'include'
    params:
      paths:
        - 'contents'
        - 'workflows/deploy-github-metrics-aggregator.yaml'
      as:
        - '{{toLowerHyphenCase .custom_name}}/deployments'
        - '.github/workflows/deploy-{{toLowerHyphenCase .custom_name}}.yaml'
  - desc: 'Replace variables'
    action: 'string_replace'
    params:
      paths:
        - '{{toLowerHyphenCase .custom_name}}/deployments'
        - '.github/workflows'
      replacements:
        - to_replace: 'REPLACE_CUSTOM_NAME'
          with: '{{toLowerHyphenCase .custom_name}}'
        - to_replace: 'REPLACE_SUBDIRECTORY'
          with: '{{toLowerHyphenCase .custom_name}}/deployments'
        - to_replace: 'REPLACE_WIF_PROVIDER'
          with: '{{.wif_provider}}'
        - to_replace: 'REPLACE_WIF_SERVICE_ACCOUNT'
          with: '{{.wif_service_account}}'
        - to_replace: 'REPLACE_FULL_IMAGE_NAME'
          with: '{{.full_image_name}}'
        - to_replace: 'REPLACE_WEBHOOK_SERVICE_NAME'
          with: '{{.webhook_service_name}}'
        - to_replace: 'REPLACE_RETRY_SERVICE_NAME'
          with: '{{.retry_service_name}}'
        - to_replace: 'REPLACE_PROJECT_ID'
          with: '{{.project_id}}'
        - to_replace: 'REPLACE_REGION'
          with: '{{.region}}'
        - to_replace: ' # REPLACE_GITHUB_METRICS_VERSION_TAG'
          with: |-
            {{- if ._git_tag -}}
              # {{._git_tag}}
            {{- else -}}
              {{._git_tag}}
            {{- end }}
        - to_replace: 'REPLACE_GITHUB_METRICS_VERSION_SHA'
          with: '{{._git_sha}}'
